### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mcuee** [libusb/hidapi#185]
Just wondering if it is already a good time for a new release.

**Comment by Youw** [comment]
some time ago I figured possible scope for new release:
https://github.com/libusb/hidapi/projects/1

**Comment by vitalys** [comment]
@Youw some time ago you wanted to release v0.9.1 that fixes #60 
So what's the current plan? Are we going to release something before v0.10.0?

**Comment by Youw** [comment]
I don't see point having anything before 0.10
According to current plan: https://github.com/libusb/hidapi/projects/1 - everything is in review, so no development/fixes is expected before 0.10.
Waiting for feedback regarding #189 from @vozhyk-com, and we good to go with 0.10.0

**Comment by Youw** [comment]
#198 will be last commit into master before firing v0.10.0
Since a bunch of commits got into master today, I think it worth having master for few more days as is, just to give at least some time to community to check its stability

if no new issues (introduced by latest commits) are going to be reported for this few days - I'll fire v0.10.0 over the weekend

**Comment by Youw** [comment]
https://github.com/libusb/hidapi/releases/tag/hidapi-0.10.0
