### ISSUE TITLE
Cannot find the lib*.so files after installed on WIndows

### ISSUE THREAD

**Issue by simonsolnes** [libusb/hidapi#267]
I built the `.sln` file in Visual Studio
After `import hid` I get

  ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

I've tried to get this library working on windows in so many different ways, what am I missing. The only method that I haven't tried is using CygWin.

Is it just me or is the Windows Drivers Kits just a garbled mess? I've followed your instructions, but the `ddl` and `so` files never seems to be in the system.

At this point, I just want to build it myself/include the files in the project, but I can't find any information on how to do that either.

**Comment by Youw** [comment]
1) When hidapi is built using Visual Studio - it does not automatically installed anywhere. That's the expected behavior for most MSVC projects by default.
2) The problem you have is a question of integration of HIDAPI and (most likely) a [cython-hidapi] python wrapper for HIDAPI. It is not directly related to this project (this is a C library implementation), and if you want to find support, I suggest first check [cython-hidapi] documentation, or try asking in their repository.

[cython-hidapi]: https://github.com/trezor/cython-hidapi

**Comment by simonsolnes** [comment]
Thank you
