### ISSUE TITLE
How does the versioning scheme apply to ABI compatibility?

### ISSUE THREAD

**Issue by hacker1024** [libusb/hidapi#292]
As far as I can tell, the versioning scheme is not documented anywhere.
Assuming that semantic versioning is in use, I'd expect the following:

Pre `1.0.0`: `0.y.a` is ABI compatible with `0.y.b`
Post `1.0.0`: `x.a.b` is ABI compatible with `x.c.d`

**Comment by Youw** [comment]
HIDAPI is being under version 0.x.y since forever, and by far I don't think we're close to 1.x.y.
Practically speaking, each new HIDAPI release always been API/ABI backward compatible with previouse releases.
There has been only one patch release (I guess current HIDAPI versioning can matches the [semantic versioning](https://semver.org/)) so far, and next release is going to be a minor version upgrade as well.

**Comment by hacker1024** [comment]
Thanks for the info.
Should this be documented somewhere (perhaps in the wiki)?

**Comment by Youw** [comment]
Added it to our [Wiki](https://github.com/libusb/hidapi/wiki)
