### ISSUE TITLE
Getting command list for hid device?

### ISSUE THREAD

**Issue by evanAndersonDigipen** [libusb/hidapi#338]
Im working with an hid device that has no documentation because it wasnt ever meant for this (its a thing from a game console) and i was curious if there was a way to retrieve all the possible commands?

**Comment by Youw** [comment]
HIDAPI isn't designed to reverse-engineer devices.

If you need to know supported reports, go parse its HID descriptor.
@todbot made an article on that: https://todbot.com/blog/2021/01/29/get-hid-report-descriptors-with-win-hid-dump-mac-hid-dump/comment-page-1/

But even knowning the report IDs and their sizes, it still won't tell you what reports does what - that information doesn't exist on HID level. That that point you can only play with it and try to guess what is it for (with high chance of braking the device, because sometime HID reports are actually changing the persistent internal state of the device).
