### ISSUE TITLE
macOS Big Sur error: OSError: open failed

### ISSUE THREAD

**Issue by MatthewMorr** [libusb/hidapi#421]
I'm trying to use hidapi on my mac but when I try to run the code: 
```
import time
import hid

VID = 0x046d
PID = 0xc07e
device = hid.device()
device.open(VID, PID)

print(device.read(1024, 1))
```
I get an error: `File "hid.pyx", line 127, in hid.device.open
OSError: open failed`
Can anyone help me with this? Thanks.

**Comment by Youw** [comment]
1) This is a `C` HIDAPI repo, and you're having an issue with `python` wrapper (looks like cython-hidapi);
2) This is a HIDAPI bug tracker, _not a support forum_;
3) VID = 0x046d, PID = 0xc07e - this looks like Logitech G402 Mouse - in 99% cases HIDAPI cannot be used with mouses/keyboards due to OS limitations on Windows and macOS;
