### ISSUE TITLE
Hotplug: feature test macro

### ISSUE THREAD

**Issue by k1-801** [libusb/hidapi#600]
I was trying to include the expected hotplug feature into the software I'm currently working on, and I encountered a problem where if the system does not have a version of hidapi with hotplug support, the headers will not have the declarations required for the target build to support the feature. In this case, I have to either ship a cached version of hidapi (which involves a risk of the software missing the next updates to the file), or re-declare them, which is unsafe unless there is a macro to test against, which is the purpose of this issue.

Would it be possible to add a #define with a feature-test macro for hotplug, and if so, what should be the name for one?

**Comment by Youw** [comment]
Hotplug is not there yet (and I'm not sure when it is going to be). I.e.: it is not released and no public distributions of it exists, unless private or enthusiastic ones.

As for feature test macros - while I'm familiar with the approach, right now HIDAPI uses a different technique, which is a version-based. I.e. new feature/API is always introduced in a new (minor) version release, and it is safe to test for a version the feature/API has been released from. E.g.:  [`hid_get_device_info`](https://github.com/libusb/hidapi/blob/d0856c05cecbb1522c24fd2f1ed1e144b001f349/hidapi/hidapi.h#L537) is available [since](https://github.com/libusb/hidapi/blob/d0856c05cecbb1522c24fd2f1ed1e144b001f349/hidapi/hidapi.h#L524) version `0.13.0`.
