### ISSUE TITLE
mistake in name

### ISSUE THREAD

**Issue by nitrologic** [libusb/hidapi#683]
https://github.com/libusb/hidapi/blame/4578ea24613af03e5631e400ed1167462702a112/mac/hid.c#L1344

I think this method should be 

hid_send_output_report

not

hid_send_output_feature_report

to match the public decl in hidapi.h[480]

**Comment by mbcinergy** [comment]
You are correct, that must have been a copy/paste error. 

Strange that the macos build pipeline does not error on this.

**Comment by Youw** [comment]
OK, I was planning on making a PR instead of pushing https://github.com/libusb/hidapi/commit/d101e5c7e4646ecde66b650b3b8ce4904acfb13a directly into master...

But since I didn't break anything (and, apparently fixed an issue) I will consider this time as an exception, and will add a protection rule to master branch to avoid such in the future.

**Comment by Youw** [comment]
> Strange that the macos build pipeline does not error on this.

And, apparently, no one is using it yet.
